[package]
name = "wavefiddler"
version = "0.1.0"
edition = "2021"

[dependencies]
fft2d = "0.1.1"
image = "0.25.5"
rustfft = "6.2.0"
plotters = "0.3.7"
hound = "3.5.1"
num-traits = "0.2.19"
log = "0.4.25"
clap = { version = "4.5.29", features = ["derive"] }

